name: paxchange
description: Simple dart script to passively synchronize installed pacman packages between systems.
version: 1.2.2
homepage: https://github.com/Skycoder42/paxchange
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

platforms:
  linux:

executables:
  paxchange:

dependencies:
  args: ^2.3.2
  dart_console: ^1.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  path: ^1.8.3
  riverpod: ^2.3.2

dev_dependencies:
  build_runner: ^2.3.3
  cider: ^0.1.5
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.8.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.24.0
  tuple: ^2.0.1

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  epoch: 2
  license: BSD
  depends:
    - pacman
  testArgs: --preset unit
  install: deploy/aur/paxchange.install
  files:
    - source: deploy/aur/config.json
      target: /etc/paxchange.json
    - source: deploy/aur/paxchange.hook
      target: /usr/share/libalpm/hooks/paxchange.hook
    - source: deploy/aur/paxchange.sysusers
      target: /usr/lib/sysusers.d/paxchange.conf
  backup:
    - etc/paxchange.json

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/paxchange/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/paxchange/compare/v%from%...v%to%
