name: paxchange
description: Simple dart script to passively synchronize installed pacman packages between systems.
version: 1.2.5
homepage: https://github.com/Skycoder42/paxchange
publish_to: none

environment:
  sdk: ^3.4.0

platforms:
  linux:

executables:
  paxchange:

dependencies:
  args: ^2.5.0
  dart_console: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.11.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  tuple: ^2.0.2

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  epoch: 2
  license: BSD
  depends:
    - pacman
  install: deploy/aur/paxchange.install
  files:
    - source: deploy/aur/config.json
      target: /etc/paxchange.json
    - source: deploy/aur/paxchange.hook
      target: /usr/share/libalpm/hooks/paxchange.hook
    - source: deploy/aur/paxchange.sysusers
      target: /usr/lib/sysusers.d/paxchange.conf
  backup:
    - etc/paxchange.json

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/paxchange/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/paxchange/compare/v%from%...v%to%
