name: pacsync
description: Simple dart script to passively synchronize installed pacman packages between systems.
version: 1.0.0
homepage: https://github.com/Skycoder42/pacsync
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

platforms:
  linux:

executables:
  pacsync:

dependencies:
  args: ^2.3.1
  freezed_annotation: ^2.1.0
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.0
  dart_pre_commit: ^3.0.2
  dart_test_tools: ^4.0.0
  freezed: ^2.1.0+1
  test: ^1.21.4
