name: pacsync
description: Simple dart script to passively synchronize installed pacman packages between systems.
version: 1.0.0
homepage: https://github.com/Skycoder42/pacsync
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dart_pre_commit: ^3.0.2
  dart_test_tools: ^4.0.0
  test: ^1.21.4
