name: paxchange
description: Simple dart script to passively synchronize installed pacman packages between systems.
version: 1.2.3
homepage: https://github.com/Skycoder42/paxchange
publish_to: none

environment:
  sdk: ^3.0.0

platforms:
  linux:

executables:
  paxchange:

dependencies:
  args: ^2.4.2
  dart_console: ^1.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  riverpod: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  dart_pre_commit: ^5.1.0+1
  dart_test_tools: ^5.1.2
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.24.3
  tuple: ^2.0.1

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  epoch: 2
  license: BSD
  depends:
    - pacman
  testArgs: --preset unit
  install: deploy/aur/paxchange.install
  files:
    - source: deploy/aur/config.json
      target: /etc/paxchange.json
    - source: deploy/aur/paxchange.hook
      target: /usr/share/libalpm/hooks/paxchange.hook
    - source: deploy/aur/paxchange.sysusers
      target: /usr/lib/sysusers.d/paxchange.conf
  backup:
    - etc/paxchange.json

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/paxchange/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/paxchange/compare/v%from%...v%to%
