name: Continuous Integration and Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      unitTestPaths: --preset unit
      coverageExclude: >-
        "**.freezed.dart"
        "**.g.dart"

  integration_tests:
    name: Integration tests
    needs:
      - ci
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install unzip
        run: pacman -Sy --noconfirm unzip
      - name: Install Dart-SDK
        uses: dart-lang/setup-dart@v1
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restore dart packages
        run: dart pub get
      - name: Create build files
        run: dart run build_runner build
      - name: Run integration tests
        run: dart test --reporter github --preset integration

  cd:
    name: CD
    needs:
      - ci
      - integration_tests
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.ci.outputs.enabledPlatforms }}
      buildRunner: true

  aur:
    name: AUR
    needs:
      - cd
    if: needs.cd.outputs.releaseCreated == 'true'
    uses: Skycoder42/dart_test_tools/.github/workflows/aur.yml@main
    secrets:
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
